[metadata]
title = "Joint Orient Offset"
id = "com.defaults.jointOrientOffset"
category = "utils"

[properties]
[properties.target]
type = "string"
format = "nodePath"
description = "Node to adjust orientation for."

[properties.offset]
type = "array"
semanticType = "VEC3"
default = [0, 0, 0]
description = "Add this XYZ value to the current orientation."
[properties.offset.items]
type = "float"
