metadata:
  title: Joint Orient Offset
  id: com.caffeine.jointOrientOffset
  category: utils
  description: Reorient a joint with the given Vector3.
properties:
  target:
    type: nodePath
    description: Node to adjust orientation for.
  offset:
    type: vector3
    description: Add this XYZ value to the current orientation.