stages:
  - name: fk_0
    steps:
      - com.caffeine.createJoint:
          position: [0, 0, 0]
          orient: [0, 0, 0]
          ssc: false
          name: "${stage0.name}"
      - com.caffeine.createControl:
          name: "${step0.response.name}_ctl"
          shape: circle
      - com.caffeine.constrain:
          target: "${step1.response.node}"
          followers:
            - "${step0.response.node}"
          maintainOffset: false
