metadata:
  title: Bone
  id: com.caffeine.bone
  category: blueprint
  description: Create a new joint node.
properties:
  name:
    type: str
    description: Name to give the new joint.
  ssc:
    type: bool
    description: Toggle segment scale compensate.
  intialTransform:
    type: transform
    description: Local transformation that this bone starts at.