[metadata]
title = "Create Control"
id = "com.defaults.createControl"
category = "dag"

[properties]
[properties.name]
type = "string"
pattern = "\w"
description = "Name of the new control object transform."
[properties.shape]
type = "string"
enum = [
    "circle",
    "square",
    "cube"
]
default = "circle"
description = "Nurbs shape to generate."
